### ISSUE TITLE
Panic when signing userOp json

### ISSUE THREAD

**Issue by blewater** [blndgs/intents-sdk#3]
I copied this from my scripts
```bash
build/intents-sdk sign --u '{
"sender": "0x60ad1b86e41863376921233fff6956150439e576",
"nonce": "0x0",
"initCode": "0x",
"callData": "{\"chainId\":80001, \"sender\":\"0x18Dd70639de2ca9146C32f9c84B90A68bBDaAA96\",\"kind\":\"swap\",\"hash\":\"\",\"sellToken\":\"0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE\",\"buyToken\":\"0xc2132D05D31c914a87C6611C10748AEb04B58e8F\",\"sellAmount\":10,\"buyAmount\":5,\"partiallyFillable\":false,\"status\":\"Received\",\"createdAt\":0,\"expirationAt\":0}",
"callGasLimit": "0x493E0",
"verificationGasLimit": "0x493E0",
"preVerificationGas": "0x493E0",
"maxFeePerGas": "0x0",
"maxPriorityFeePerGas": "0x0",
"paymasterAndData": "0x",
"signature": ""
}'
Signer private key: 0x860304ed3cb246bd492a84510742b5fd42358968e60e3ff9e9f8287b24a05f6a
Public key: 5b4258c6914408f003fccd952645fc9c64b5eb4dde18fa2d7252fcde8f0c73bc391d4c29c35631e5e5a0bc35721e6f17819e28bf25021d047c81997453a92656
Address: 0xa4BFe126D3aD137F972695dDdb1780a29065e556
Entrypoint Address: 0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789
panic: error parsing user operation JSON: empty hex string

goroutine 1 [running]:
github.com/blndgs/intents-sdk/utils.GetUserOps(0x49cdfdb0d437f15f?)
        /Users/mar/go/src/github.com/blndgs/intents-sdk/utils/common.go:64 +0x104
github.com/blndgs/intents-sdk/cmd.glob..func3(0x14000538800?, {0x102e19202?, 0x4?, 0x102e19206?})
        /Users/mar/go/src/github.com/blndgs/intents-sdk/cmd/sign_userop.go:30 +0x6c
github.com/spf13/cobra.(*Command).execute(0x1033d8ec0, {0x14000127160, 0x2, 0x2})
        /Users/mar/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x654
github.com/spf13/cobra.(*Command).ExecuteC(0x14000142600)
        /Users/mar/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/mar/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
        /Users/mar/go/src/github.com/blndgs/intents-sdk/main.go:24 +0xd4
```

**Comment by singhhp1069** [comment]
This panic is because signature is empty that is mandatory field by model and unmarshing giving error:

https://github.com/blndgs/model/blob/d1daed6a2d3a612f6967880a39ddb19943cc98d0/userops.go#L59

should we remove validate or maintain a seperate struct in SDK?

**Comment by blewater** [comment]
> This panic is because signature is empty that is mandatory field by model and unmarshing giving error:
> 
> https://github.com/blndgs/model/blob/d1daed6a2d3a612f6967880a39ddb19943cc98d0/userops.go#L59
> 
> https://github.com/blndgs/intents-sdk/blob/aca334235729ee23f74b72f800a7e370e3f292b8/utils/common.go#L60
> 
> should we remove validate or maintain a seperate struct in SDK?

Gotcha, we can detect being empty and insert an acceptable 0 value, i.e., allocated empty or '0x' or '0x0'. 
Considering the SDK's public profile usage, it's not good UX to require the user to fill it out with a placeholder for an unsigned userOp.
What do you think?
